import { Injectable, Logger } from '@nestjs/common';
import { ProactiveAlert } from '@couchy/shared';
import { GraphService } from '../graph/graph.service';

@Injectable()
export class AlertsService {
  private readonly logger = new Logger(AlertsService.name);

  // Per-session alert store (newest-first)
  private alertsBySession = new Map<string, ProactiveAlert[]>();

  // Per-session question counter per node for gap detection
  private questionCounters = new Map<string, number>();

  constructor(private readonly graph: GraphService) {}

  // ---------------------------------------------------------------------------
  // Public API used by controller
  // ---------------------------------------------------------------------------

  getAlerts(sessionId: string): ProactiveAlert[] {
    return this.alertsBySession.get(sessionId) ?? [];
  }

  /**
   * Store alerts that were generated by AgentService during a stream.
   * Called after each chat message is processed.
   */
  storeAlerts(sessionId: string, alerts: ProactiveAlert[]): void {
    if (alerts.length === 0) return;

    const existing = this.alertsBySession.get(sessionId) ?? [];

    // Deduplicate by type+relatedNodes combo (avoid double-storing same alert in rapid succession)
    const dedupedNew = alerts.filter((incoming) => {
      return !existing.some(
        (e) =>
          e.type === incoming.type &&
          e.relatedNodes.join(',') === incoming.relatedNodes.join(',') &&
          // Only deduplicate within last 30 seconds
          Date.now() - new Date(e.createdAt).getTime() < 30_000,
      );
    });

    if (dedupedNew.length === 0) return;

    // Newest first
    this.alertsBySession.set(sessionId, [...dedupedNew, ...existing]);
    this.logger.log(`Stored ${dedupedNew.length} new alerts for session ${sessionId}`);
  }

  // ---------------------------------------------------------------------------
  // Gap Detection (tracks per-session question frequency per graph node)
  // ---------------------------------------------------------------------------

  /**
   * Call this every time a user asks a question mentioning a node.
   * Returns new gap alerts if threshold crossed.
   */
  checkGaps(sessionId: string, nodeIds: string[]): ProactiveAlert[] {
    const newAlerts: ProactiveAlert[] = [];

    for (const nodeId of nodeIds) {
      const key = `${sessionId}::${nodeId}`;
      const count = (this.questionCounters.get(key) ?? 0) + 1;
      this.questionCounters.set(key, count);

      if (count === 3) {
        // Exactly at threshold — create gap alert once
        const node = this.graph.getNode(nodeId);
        const label = node?.label ?? nodeId;

        const alert: ProactiveAlert = {
          id: `gap_${nodeId}_${Date.now()}`,
          type: 'gap_detected',
          title: `⚠️ Gap обнаружен: ${label}`,
          body: `Вопрос по "${label}" задан уже ${count} раза в этой сессии. Рекомендуется улучшить документацию или провести синк с командой.`,
          relatedNodes: [nodeId],
          createdAt: new Date().toISOString(),
        };

        newAlerts.push(alert);
        this.storeAlerts(sessionId, [alert]);

        this.logger.warn(`Gap detected: node="${nodeId}", session="${sessionId}", count=${count}`);
      }
    }

    return newAlerts;
  }

  // ---------------------------------------------------------------------------
  // Proactive Dependency Alerts
  // ---------------------------------------------------------------------------

  /**
   * Analyse userMessage for modification intent on known services.
   * Returns alerts if dependency risks are found.
   */
  checkDependencyAlerts(sessionId: string, userMessage: string): ProactiveAlert[] {
    const msg = userMessage.toLowerCase();
    const alerts: ProactiveAlert[] = [];

    const modificationKeywords = [
      'изменил', 'правлю', 'меняю', 'рефакторинг',
      'удалил', 'добавил', 'change', 'modif', 'refactor',
      'update', 'delete', 'remove', 'edit',
    ];
    const isModifying = modificationKeywords.some((kw) => msg.includes(kw));

    if (!isModifying) return [];

    // Check each "critical" service node
    const criticalNodes = ['UserService', 'AuthService'];
    for (const nodeId of criticalNodes) {
      if (!msg.includes(nodeId.toLowerCase())) continue;

      const neighbors = this.graph.getNeighbors(nodeId);
      if (neighbors.length === 0) continue;

      const relatedIds = [nodeId, ...neighbors.map((n) => n.node.id)];
      const neighborLabels = neighbors
        .filter((n) => n.direction === 'in' || n.direction === 'out')
        .map((n) => `${n.node.label} (${n.relation})`)
        .join(', ');

      const alert: ProactiveAlert = {
        id: `dep_${nodeId}_${Date.now()}`,
        type: 'dependency_warning',
        title: `⚠️ Зависимость: ${nodeId}`,
        body: `"${nodeId}" связан с: ${neighborLabels}. Изменения могут вызвать каскадные проблемы. Проверь ТЗ-047.`,
        relatedNodes: relatedIds,
        createdAt: new Date().toISOString(),
      };

      alerts.push(alert);
    }

    if (alerts.length > 0) {
      this.storeAlerts(sessionId, alerts);
    }

    return alerts;
  }

  /**
   * Get question count for a node in a session.
   */
  getQuestionCount(sessionId: string, nodeId: string): number {
    return this.questionCounters.get(`${sessionId}::${nodeId}`) ?? 0;
  }
}
